name: "Test"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30
    - name: Set up Nix cache
      uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
    - run: nix-build test.nix
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30
    - name: Set up Nix cache
      uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
    - run: nix-build test.nix
